/**
 * Core abstraction for browser‑based computer control.
 * Implementations must be safe, deterministic and respect the policy engine.
 */
export interface Observation {
  /** Current page URL */
  url: string;
  /** Page title */
  title: string;
  /** Visible text content of the page */
  visibleText: string;
  /** Interactive elements on the page */
  interactiveElements: Array<{
    elementId: string; // stable identifier generated by the provider
    role: string; // e.g., "button", "link", "textbox"
    text?: string;
    ariaLabel?: string;
    tag: string;
    visible: boolean;
    enabled: boolean;
  }>;
  /** Forms present on the page */
  forms: Array<{
    formId: string;
    fields: Array<{ fieldId: string; name: string; type: string; label?: string }>;
  }>;
  /** Timestamp of observation */
  timestamp: string;
}

/**
 * ProviderState indicates whether the implementation is a real Playwright
 * driver, a mock used for tests, or unavailable (e.g., missing binary).
 */
export enum ProviderState {
  REAL = "REAL",
  MOCK = "MOCK",
  UNAVAILABLE = "UNAVAILABLE",
}

/**
 * Interface that all computer‑control providers must implement.
 */
export interface ComputerControlProvider {
  /** Create a new isolated browser session and return its ID */
  createSession(): Promise<string>;

  /** Observe the current state of the page in a session */
  observe(sessionId: string): Promise<Observation>;

  /** Navigate the session to a URL */
  navigate(sessionId: string, url: string): Promise<void>;

  /** Click an element identified by the stable elementId */
  click(sessionId: string, elementId: string): Promise<void>;

  /** Type text into a textbox identified by elementId */
  type(sessionId: string, elementId: string, text: string): Promise<void>;

  /** Fill a form with a map of fieldId -> value */
  fill(sessionId: string, data: Record<string, string>): Promise<void>;

  /** Scroll the page vertically by deltaY pixels */
  scroll(sessionId: string, deltaY: number): Promise<void>;

  /** Wait for a specified amount of milliseconds */
  wait(sessionId: string, ms: number): Promise<void>;

  /** Navigate back in history */
  goBack(sessionId: string): Promise<void>;

  /** Navigate forward in history */
  goForward(sessionId: string): Promise<void>;

  /** Capture a screenshot, returning a path to the saved image */
  screenshot(sessionId: string): Promise<string>;

  /** Close the session and clean up resources */
  close(sessionId: string): Promise<void>;

  /** Return the current provider state (REAL, MOCK, UNAVAILABLE) */
  getState(): ProviderState;
}
